// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heufkcuzexsjxfcsgzaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldWZrY3V6ZXhzanhmY3NnemFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjAzMjIsImV4cCI6MjA3MDczNjMyMn0.EEcydjqBC_yUq5UV_PYd0DHgGKsa8SDlAAKRMsgDqiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});